version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

# Equivalent to `pip install .[docs]`
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  # install:
  #   - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  # fail_on_warning: true
